<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <EmbeddedResource Include="Samples/HelloCard.axaml.txt" />
    <EmbeddedResource Include="Samples/HelloCardCode.txt" />
    <EmbeddedResource Include="Samples/HelloCardViewModel.txt" />
    <PackageReference Include="AvaloniaEdit.TextMate" Version="12.0.0" />
    <PackageReference Include="Material3.Avalonia" Version="0.2.0-preview.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
  </ItemGroup>
</Project>
